export const FORM_VALIDATE = 'FORM_VALIDATE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const FORM_SUBMIT = 'FORM_SUBMIT';
export const VALIDATE_COMPLETE = 'VALIDATE_COMPLETE';
export const VALIDATE_INCOMPLETE = 'VALIDATE_INCOMPLETE';
export const TRIGGER_BACK = 'TRIGGER_BACK'
export const CLEAR_FORM_BACK = 'CLEAR_FORM_BACK'
export const DATA_CALCULATION = 'DATA_CALCULATION'